[Integer.rust]
depends = ["num"]
once = "use num::bigint::BigInt;"
parse = "pub struct {$0}(BigInt);"
derive = ""


[String.rust]
depends= []
parse= "pub struct {$0}(String);",
derive= [""]

[Integer.rust]
depends= []

[u8.rust]
parse = "u8"
derive =  ""